# Generated by Django 4.2.3 on 2024-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Please keep it Blank for Auto Url', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Please keep it Blank for Auto Url', max_length=200, unique=True),
        ),
    ]
