# Generated by Django 4.2.11 on 2024-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=True, help_text='Used to Select Wheather to Show comment or not'),
        ),
    ]
