# Generated by Django 4.2.11 on 2024-09-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
