# Generated by Django 4.2.11 on 2024-09-25 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='liked_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
